mailerdb:
  container_name: mailerdb
  image: postgres:9
  ports:
    - 5432:5432
  environment:
    POSTGRES_DB: mailerdb
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: p4ssword
cache:
  container_name: redis
  image: redis
  ports:
    - 6379:6379
mailhog:
  container_name: mailhog
  image: mailhog/mailhog
  ports:
    - 1025:1025
    - 8025:8025